# Generated by Django 4.0 on 2022-01-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homemodels', '0003_rename_name_prodcatglist_subcatg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviewform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.PositiveBigIntegerField()),
                ('message', models.TextField()),
                ('rating', models.CharField(max_length=10)),
                ('submit_time', models.TimeField()),
            ],
        ),
    ]
