# Generated by Django 4.0 on 2022-01-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homemodels', '0004_reviewform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewform',
            name='submit_time',
            field=models.DateTimeField(),
        ),
    ]
