# Generated by Django 4.0 on 2021-12-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allcatgprods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='top_stock_trading_and_investments_apps',
            name='appimg',
            field=models.ImageField(default='defaultimg/', upload_to='top_stock_trading_and_investments_apps/img/', verbose_name='Product image'),
        ),
    ]
