# Generated by Django 4.0 on 2022-01-01 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allcatgprods', '0002_top_stock_trading_and_investments_apps_appimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='top_stock_trading_and_investments_apps',
            old_name='appname',
            new_name='name',
        ),
    ]
