# Generated by Django 4.0 on 2022-01-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allcatgprods', '0003_rename_appname_top_stock_trading_and_investments_apps_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of App')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='User Rating')),
                ('pros', models.TextField(max_length=500, verbose_name="Enter Pros (using'/'to seperate)")),
                ('cons', models.TextField(max_length=500, verbose_name="Enter Cons (using'/'to seperate)")),
                ('upr', models.TextField(verbose_name="Users +ve review(using'/'to seperate)")),
                ('unr', models.TextField(verbose_name="Users -ve review(using'/'to seperate)")),
                ('youtubelink', models.URLField(verbose_name='Youtube Reveiw/Comparision link')),
                ('rank', models.PositiveSmallIntegerField(verbose_name='Rank of product')),
                ('model', models.CharField(max_length=15, verbose_name='Model No.')),
                ('weight', models.CharField(max_length=10, verbose_name='Items Weight')),
                ('color', models.CharField(max_length=10, verbose_name='Colour')),
                ('os', models.CharField(max_length=20, verbose_name='Operating system')),
                ('bb', models.CharField(max_length=10, verbose_name='Battery Backup')),
                ('proc', models.CharField(max_length=50, verbose_name='Processor')),
                ('gproc', models.CharField(max_length=50, verbose_name='Graphic processor')),
                ('ram', models.CharField(max_length=15, verbose_name='Ram Capacity')),
                ('ramspeed', models.CharField(max_length=10, verbose_name='Ram Speed')),
                ('ssd', models.CharField(max_length=10, verbose_name='SSD Capacity')),
                ('cache', models.CharField(max_length=10, verbose_name='Cache')),
                ('exmem', models.CharField(max_length=10, verbose_name='Expandable Memory')),
                ('noc', models.CharField(max_length=2, verbose_name='Number of cores')),
                ('dispsize', models.CharField(max_length=15, verbose_name='Display Size')),
                ('dispres', models.CharField(max_length=15, verbose_name='Display Resolution')),
                ('touchscr', models.CharField(max_length=5, verbose_name='Touch Screen')),
                ('disptype', models.CharField(max_length=15, verbose_name='Display type')),
                ('webcam', models.CharField(max_length=15, verbose_name='Web-Cam')),
                ('mic', models.CharField(max_length=10, verbose_name='In-built Microphone')),
                ('speakers', models.CharField(max_length=20, verbose_name='Speakers')),
                ('usbport', models.CharField(max_length=40, verbose_name='USB ports')),
                ('hdmiport', models.CharField(max_length=40, verbose_name='HDMI ports')),
                ('backlit', models.CharField(max_length=5, verbose_name='Backlit Keyboard')),
                ('fingerprint', models.CharField(max_length=5, verbose_name='Fingerprint Scanner')),
                ('retina', models.CharField(max_length=5, verbose_name='Retina Scanner')),
                ('warrenty', models.CharField(max_length=10, verbose_name='Warrenty')),
                ('amazonp', models.CharField(max_length=20, verbose_name='Price on Amazon')),
                ('amazonlink', models.URLField(verbose_name='Amazon Link')),
                ('flipkartp', models.CharField(max_length=20, verbose_name='Price on Flipkart')),
                ('flipkartlink', models.URLField(verbose_name='Flipkart link')),
                ('officialp', models.CharField(max_length=20, verbose_name='Price on Official store')),
                ('officiallink', models.URLField(verbose_name='Official link')),
                ('reliancep', models.CharField(max_length=20, verbose_name='Price on Reliance Digital')),
                ('reliancelink', models.URLField(verbose_name='Reliance Link')),
                ('minp', models.PositiveIntegerField(verbose_name='Minimum Price')),
                ('minplink', models.URLField(verbose_name='Minimum Price Link')),
                ('minpseller', models.CharField(max_length=20, verbose_name='Minimum Price Seller')),
                ('spclcatg', models.CharField(max_length=15, verbose_name='Special Category')),
                ('prodimg', models.ImageField(default='defaultimg/', upload_to='laptop/img/', verbose_name='Product image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
