# Generated by Django 4.0 on 2022-01-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allcatgprods', '0006_rename_exmem_laptop_graphiccard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='bb',
            field=models.CharField(max_length=20, verbose_name='Battery Backup'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='color',
            field=models.CharField(max_length=20, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='minpseller',
            field=models.CharField(max_length=50, verbose_name='Minimum Price Seller'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='model',
            field=models.CharField(max_length=30, verbose_name='Model No.'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='refreshrate',
            field=models.CharField(max_length=15, verbose_name='Ram Speed'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='spclcatg',
            field=models.CharField(max_length=25, verbose_name='Special Category'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ssd',
            field=models.CharField(max_length=20, verbose_name='SSD Capacity'),
        ),
    ]
