# Generated by Django 4.0 on 2022-01-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allcatgprods', '0009_alter_laptop_prodimg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Product')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='User Rating')),
                ('pros', models.TextField(max_length=500, verbose_name="Enter Pros (using'/'to seperate)")),
                ('cons', models.TextField(max_length=500, verbose_name="Enter Cons (using'/'to seperate)")),
                ('upr', models.TextField(verbose_name="Users +ve review(using'/'to seperate)")),
                ('unr', models.TextField(verbose_name="Users -ve review(using'/'to seperate)")),
                ('youtubelink', models.URLField(verbose_name='Youtube Reveiw/Comparision link')),
                ('amazonp', models.CharField(max_length=40, verbose_name='Price on Amazon')),
                ('amazonlink', models.URLField(verbose_name='Amazon Link')),
                ('flipkartp', models.CharField(max_length=40, verbose_name='Price on Flipkart')),
                ('flipkartlink', models.URLField(verbose_name='Flipkart link')),
                ('officialp', models.CharField(max_length=40, verbose_name='Price on Official store')),
                ('officiallink', models.URLField(verbose_name='Official link')),
                ('minp', models.PositiveIntegerField(verbose_name='Minimum Price')),
                ('minplink', models.URLField(verbose_name='Minimum Price Link')),
                ('minpseller', models.CharField(max_length=50, verbose_name='Minimum Price Seller')),
                ('rank', models.PositiveSmallIntegerField(verbose_name='Rank of product')),
                ('model', models.CharField(max_length=30, verbose_name='Model No.')),
                ('weight', models.CharField(max_length=10, verbose_name='Items Weight')),
                ('color', models.CharField(max_length=20, verbose_name='Colour')),
                ('os', models.CharField(max_length=20, verbose_name='Operating system')),
                ('bb', models.CharField(max_length=20, verbose_name='Battery Backup')),
                ('proc', models.CharField(max_length=50, verbose_name='Processor')),
                ('clockspeed', models.CharField(max_length=200, verbose_name='Processor Clock speed')),
                ('gproc', models.CharField(max_length=50, verbose_name='Graphic processor')),
                ('ram', models.CharField(max_length=25, verbose_name='Ram Capacity')),
                ('simslot', models.CharField(max_length=100, verbose_name='Sim card Slot')),
                ('memoryslot', models.CharField(max_length=50, verbose_name='Memory Slots')),
                ('dispsize', models.CharField(max_length=50, verbose_name='Display Size')),
                ('dispres', models.CharField(max_length=50, verbose_name='Display Resolution')),
                ('fingerscan', models.CharField(max_length=20, verbose_name='Touch Screen')),
                ('facescan', models.CharField(max_length=20, verbose_name='Face scan')),
                ('speakers', models.CharField(max_length=80, verbose_name='Speakers')),
                ('camera', models.CharField(max_length=150, verbose_name='Camera details')),
                ('videorec', models.CharField(max_length=100, verbose_name='Video Recording')),
                ('spclcatg', models.CharField(max_length=50, verbose_name='Special Category')),
                ('metallicbody', models.CharField(max_length=30, verbose_name='Metallic Body')),
                ('warrenty', models.CharField(max_length=50, verbose_name='Warrenty')),
                ('reliancep', models.CharField(max_length=40, verbose_name='Price on Reliance Digital')),
                ('reliancelink', models.URLField(verbose_name='Reliance Link')),
                ('prodimg', models.ImageField(default='defaultimg/', upload_to='e_commerce/mobile/img/', verbose_name='Product image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='laptop',
            name='amazonp',
            field=models.CharField(max_length=40, verbose_name='Price on Amazon'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='flipkartp',
            field=models.CharField(max_length=40, verbose_name='Price on Flipkart'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='officialp',
            field=models.CharField(max_length=40, verbose_name='Price on Official store'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='reliancep',
            field=models.CharField(max_length=40, verbose_name='Price on Reliance Digital'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='spclcatg',
            field=models.CharField(max_length=50, verbose_name='Special Category'),
        ),
    ]
