# Generated by Django 4.0 on 2022-01-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allcatgprods', '0012_camera'),
    ]

    operations = [
        migrations.CreateModel(
            name='smart_tv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Product')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='User Rating')),
                ('pros', models.TextField(max_length=500, verbose_name="Enter Pros (using'/'to seperate)")),
                ('cons', models.TextField(max_length=500, verbose_name="Enter Cons (using'/'to seperate)")),
                ('upr', models.TextField(verbose_name="Users +ve review(using'/'to seperate)")),
                ('unr', models.TextField(verbose_name="Users -ve review(using'/'to seperate)")),
                ('youtubelink', models.URLField(verbose_name='Youtube Reveiw/Comparision link')),
                ('amazonp', models.CharField(max_length=40, verbose_name='Price on Amazon')),
                ('amazonlink', models.URLField(verbose_name='Amazon Link')),
                ('flipkartp', models.CharField(max_length=40, verbose_name='Price on Flipkart')),
                ('flipkartlink', models.URLField(verbose_name='Flipkart link')),
                ('officialp', models.CharField(max_length=40, verbose_name='Price on Official store')),
                ('officiallink', models.URLField(verbose_name='Official link')),
                ('minp', models.PositiveIntegerField(verbose_name='Minimum Price')),
                ('minplink', models.URLField(verbose_name='Minimum Price Link')),
                ('minpseller', models.CharField(max_length=50, verbose_name='Minimum Price Seller')),
                ('rank', models.PositiveSmallIntegerField(verbose_name='Rank of product')),
                ('model', models.CharField(max_length=30, verbose_name='Model No.')),
                ('dispsize', models.CharField(max_length=50, verbose_name='Display Size')),
                ('dispres', models.CharField(max_length=50, verbose_name='Display Resolution')),
                ('dispresstd', models.CharField(max_length=50, verbose_name='Display Resolution std')),
                ('color', models.CharField(max_length=50, verbose_name='Product color')),
                ('smarttv', models.CharField(max_length=50, verbose_name='Is it smart Tv')),
                ('noofspeakers', models.CharField(max_length=50, verbose_name='No. of Speakers')),
                ('speakername', models.CharField(max_length=150, verbose_name='Name of Speaker')),
                ('noofcores', models.CharField(max_length=50, verbose_name='No. of Cores')),
                ('ram', models.CharField(max_length=50, verbose_name='Ram')),
                ('internalstorage', models.CharField(max_length=100, verbose_name='Internal storage')),
                ('os', models.CharField(max_length=100, verbose_name='Operating system of T.v')),
                ('supportedapps', models.CharField(max_length=200, verbose_name='Supported apps(list)')),
                ('warrenty', models.CharField(max_length=150, verbose_name='Warrenty')),
                ('prodimg', models.ImageField(default='defaultimg/', upload_to='e_commerce/camera/img/', verbose_name='Product image')),
                ('reliancep', models.CharField(max_length=40, verbose_name='Price on Reliance Digital')),
                ('reliancelink', models.URLField(verbose_name='Reliance Link')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
