# Generated by Django 4.0 on 2022-01-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allcatgprods', '0015_crypto_trading_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='crypto_trading_apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Product')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='User Rating')),
                ('pros', models.TextField(max_length=500, verbose_name="Enter Pros (using'/'to seperate)")),
                ('cons', models.TextField(max_length=500, verbose_name="Enter Cons (using'/'to seperate)")),
                ('upr', models.TextField(verbose_name="Users +ve review(using'/'to seperate)")),
                ('unr', models.TextField(verbose_name="Users -ve review(using'/'to seperate)")),
                ('youtubelink', models.URLField(verbose_name='Youtube Reveiw/Comparision link')),
                ('rank', models.PositiveSmallIntegerField(verbose_name='App Rank')),
                ('aoc', models.PositiveSmallIntegerField(verbose_name='Account opening charge')),
                ('cryptoavialable', models.PositiveSmallIntegerField(verbose_name='No. of Cryptos avialable')),
                ('makerfees', models.CharField(max_length=50, verbose_name='Maker fees (in percent)')),
                ('takerfees', models.CharField(max_length=50, verbose_name='Taker fees (in percent)')),
                ('withdrawlfees', models.CharField(max_length=50, verbose_name='Withdrawl fees (in BTC)')),
                ('minwdllimit', models.CharField(max_length=50, verbose_name='Minimum withdrawl limit (in BTC)')),
                ('est', models.PositiveSmallIntegerField(verbose_name='Establishment Year')),
                ('applink', models.URLField(verbose_name='App/Website link')),
                ('appimg', models.ImageField(default='defaultimg/', upload_to='fintech/crypto_trading_apps/img/', verbose_name='Product image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
