# Generated by Django 4.0 on 2022-01-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allcatgprods', '0016_crypto_trading_apps'),
    ]

    operations = [
        migrations.CreateModel(
            name='online_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Product')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='User Rating')),
                ('pros', models.TextField(max_length=500, verbose_name="Enter Pros (using'/'to seperate)")),
                ('cons', models.TextField(max_length=500, verbose_name="Enter Cons (using'/'to seperate)")),
                ('upr', models.TextField(verbose_name="Users +ve review(using'/'to seperate)")),
                ('unr', models.TextField(verbose_name="Users -ve review(using'/'to seperate)")),
                ('youtubelink', models.URLField(verbose_name='Youtube Reveiw/Comparision link')),
                ('coursecatg', models.CharField(max_length=200, verbose_name='Category name of course')),
                ('rank', models.PositiveSmallIntegerField(verbose_name='App Rank')),
                ('designedfor', models.CharField(max_length=100, verbose_name='Designed/Suitable for')),
                ('courselength', models.CharField(max_length=100, verbose_name='Course length')),
                ('coursefees', models.CharField(max_length=100, verbose_name='Course Fees')),
                ('coursecertificate', models.CharField(max_length=200, verbose_name='Course include certificate ?')),
                ('studentscompleted', models.CharField(max_length=150, verbose_name='No. of Students Completed')),
                ('courseplatform', models.CharField(max_length=100, verbose_name='Course platform')),
                ('courseteacher', models.CharField(max_length=300, verbose_name='Course teacher name & details')),
                ('prerequisite', models.CharField(max_length=250, verbose_name='Prerequisite of course')),
                ('courselink', models.URLField(verbose_name='Course Link')),
                ('prodimg', models.ImageField(default='defaultimg/', upload_to='fintech/<django.db.models.fields.CharField>/img/', verbose_name='Course image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='crypto_trading_course',
        ),
    ]
