# Generated by Django 4.0 on 2021-12-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homemodels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodcatglist',
            name='catgimg',
            field=models.ImageField(default='defaultimg/', upload_to='homepage/img/'),
        ),
    ]
