# Generated by Django 4.0 on 2022-01-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allcatgprods', '0004_laptop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name of Product'),
        ),
        migrations.AlterField(
            model_name='top_stock_trading_and_investments_apps',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name of Product'),
        ),
    ]
