# Generated by Django 4.0 on 2022-01-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allcatgprods', '0005_alter_laptop_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='exmem',
            new_name='graphiccard',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='ramspeed',
            new_name='refreshrate',
        ),
        migrations.AddField(
            model_name='laptop',
            name='clockspeed',
            field=models.CharField(default=0, max_length=200, verbose_name='Processor Clock speed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laptop',
            name='disptype',
            field=models.CharField(max_length=150, verbose_name='Display type'),
        ),
    ]
