# Generated by Django 4.0 on 2022-01-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allcatgprods', '0007_alter_laptop_bb_alter_laptop_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='backlit',
            field=models.CharField(max_length=25, verbose_name='Backlit Keyboard'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='dispres',
            field=models.CharField(max_length=50, verbose_name='Display Resolution'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='dispsize',
            field=models.CharField(max_length=50, verbose_name='Display Size'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='fingerprint',
            field=models.CharField(max_length=20, verbose_name='Fingerprint Scanner'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='graphiccard',
            field=models.CharField(max_length=10, verbose_name='Graphic card Memory'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='hdmiport',
            field=models.CharField(max_length=150, verbose_name='HDMI ports'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='mic',
            field=models.CharField(max_length=50, verbose_name='In-built Microphone'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='refreshrate',
            field=models.CharField(max_length=15, verbose_name='Refresh rate'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='retina',
            field=models.CharField(max_length=20, verbose_name='Retina Scanner'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='speakers',
            field=models.CharField(max_length=80, verbose_name='Speakers'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='usbport',
            field=models.CharField(max_length=150, verbose_name='USB ports'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='warrenty',
            field=models.CharField(max_length=50, verbose_name='Warrenty'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='webcam',
            field=models.CharField(max_length=50, verbose_name='Web-Cam'),
        ),
    ]
