# Generated by Django 4.0 on 2022-01-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allcatgprods', '0008_alter_laptop_backlit_alter_laptop_dispres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='prodimg',
            field=models.ImageField(default='defaultimg/', upload_to='e_commerce/laptop/img/', verbose_name='Product image'),
        ),
        migrations.AlterField(
            model_name='top_stock_trading_and_investments_apps',
            name='appimg',
            field=models.ImageField(default='defaultimg/', upload_to='fintech/top_stock_trading_and_investments_apps/img/', verbose_name='Product image'),
        ),
    ]
