# Generated by Django 4.0 on 2022-01-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allcatgprods', '0018_earpod'),
    ]

    operations = [
        migrations.CreateModel(
            name='trimmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Product')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='User Rating')),
                ('pros', models.TextField(max_length=500, verbose_name="Enter Pros (using'/'to seperate)")),
                ('cons', models.TextField(max_length=500, verbose_name="Enter Cons (using'/'to seperate)")),
                ('upr', models.TextField(verbose_name="Users +ve review(using'/'to seperate)")),
                ('unr', models.TextField(verbose_name="Users -ve review(using'/'to seperate)")),
                ('youtubelink', models.URLField(verbose_name='Youtube Reveiw/Comparision link')),
                ('amazonp', models.CharField(max_length=40, verbose_name='Price on Amazon')),
                ('amazonlink', models.URLField(verbose_name='Amazon Link')),
                ('flipkartp', models.CharField(max_length=40, verbose_name='Price on Flipkart')),
                ('flipkartlink', models.URLField(verbose_name='Flipkart link')),
                ('officialp', models.CharField(max_length=40, verbose_name='Price on Official store')),
                ('officiallink', models.URLField(verbose_name='Official link')),
                ('minp', models.PositiveIntegerField(verbose_name='Minimum Price')),
                ('minplink', models.URLField(verbose_name='Minimum Price Link')),
                ('minpseller', models.CharField(max_length=50, verbose_name='Minimum Price Seller')),
                ('rank', models.PositiveSmallIntegerField(verbose_name='Rank of product')),
                ('model', models.CharField(max_length=30, verbose_name='Model No.')),
                ('batteryruntime', models.CharField(max_length=100, verbose_name='Run time in Full charge')),
                ('chargingtime', models.CharField(max_length=50, verbose_name='Charging time(for full)')),
                ('color', models.CharField(max_length=50, verbose_name='Product color')),
                ('washablehead', models.CharField(max_length=200, verbose_name='Washable head')),
                ('waterresistant', models.CharField(max_length=150, verbose_name='Waterproof details')),
                ('lengthadjustment', models.CharField(max_length=50, verbose_name='How many length adjustment')),
                ('warrenty', models.CharField(max_length=150, verbose_name='Warrenty')),
                ('prodimg', models.ImageField(default='defaultimg/', upload_to='e_commerce/trimmer/img/', verbose_name='Product image')),
                ('reliancep', models.CharField(max_length=40, verbose_name='Price on Reliance Digital')),
                ('reliancelink', models.URLField(verbose_name='Reliance Link')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='earphone',
            name='prodimg',
            field=models.ImageField(default='defaultimg/', upload_to='e_commerce/earphone/img/', verbose_name='Product image'),
        ),
        migrations.AlterField(
            model_name='earpod',
            name='prodimg',
            field=models.ImageField(default='defaultimg/', upload_to='e_commerce/earpod/img/', verbose_name='Product image'),
        ),
        migrations.AlterField(
            model_name='headphone',
            name='prodimg',
            field=models.ImageField(default='defaultimg/', upload_to='e_commerce/headphone/img/', verbose_name='Product image'),
        ),
        migrations.AlterField(
            model_name='smart_tv',
            name='prodimg',
            field=models.ImageField(default='defaultimg/', upload_to='e_commerce/smart_tv/img/', verbose_name='Product image'),
        ),
    ]
