# Generated by Django 4.0 on 2022-01-17 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allcatgprods', '0019_trimmer_alter_earphone_prodimg_alter_earpod_prodimg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earpod',
            old_name='inbuitmic',
            new_name='inbuiltmic',
        ),
    ]
