# Generated by Django 4.0 on 2022-01-24 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allcatgprods', '0020_rename_inbuitmic_earpod_inbuiltmic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='top_stock_trading_and_investments_apps',
            new_name='best_stock_trading_apps',
        ),
    ]
