# Generated by Django 4.0 on 2022-01-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allcatgprods', '0021_rename_top_stock_trading_and_investments_apps_best_stock_trading_apps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='backlit',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='cache',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='clockspeed',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='color',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='dispres',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='disptype',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='fingerprint',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='gproc',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='graphiccard',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='hdmiport',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='mic',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='model',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='noc',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='refreshrate',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='retina',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='speakers',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='ssd',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='touchscr',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='usbport',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='warrenty',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='webcam',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='weight',
        ),
        migrations.AddField(
            model_name='laptop',
            name='memory',
            field=models.CharField(default=0, max_length=15, verbose_name='Ram+SSD+cache'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='specialfeatures',
            field=models.CharField(default=0, max_length=200, verbose_name='Add special features(scans,backlit)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laptop',
            name='proc',
            field=models.CharField(max_length=50, verbose_name='Processor+Clockspeed'),
        ),
    ]
